### ISSUE TITLE
Old Certificate not being removed resulting in errors during deployment

### ISSUE THREAD

**Issue by rubenmamo** [condep/condep-node#1] opened 2016-03-18 13:52 UTC
It's been a year since we started to use ConDep on our production environment and now we're getting errors when trying to deploy applications related to the certificate that Condep Node uses to secure the api.

The error we're getting is

```
Step 1/1: Deploy (Command Line) (25s)
[14:43:54][Step 1/1] Executing pre-operations (6s)
[14:43:54][Executing pre-operations] *******(6s)
[14:43:54][*******] Pre-Operations (6s)
[14:43:55][Pre-Operations] Validating ConDepNode (6s)
[14:44:01]
[Validating ConDepNode] Failed to connect to ConDep Node!
Message: One or more errors occurred.

Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ConDep.Dsl.Remote.Node.Api.Validate()
[14:44:01]
[Validating ConDepNode] Failed to connect to ConDep Node!
Message: One or more errors occurred.

Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ConDep.Dsl.Remote.Node.Api.Validate()
[14:44:01]
[Step 1/1] ConDep execution failed.
Message: Unable to make contact with ConDep Node or return content from API.

Stack Trace:
   at ConDep.Dsl.PreRemoteOps.<>c__DisplayClass18.<PublishConDepNode>b__17()
   at ConDep.Dsl.Logging.Logger.WithLogSection(String sectionName, Action action)
   at ConDep.Dsl.PreRemoteOps.PublishConDepNode(ServerConfig server, ConDepSettings settings)
   at ConDep.Dsl.PreRemoteOps.<>c__DisplayClass3.<Execute>b__0()
   at ConDep.Dsl.Logging.Logger.WithLogSection(String sectionName, Action action)
   at ConDep.Dsl.PreRemoteOps.Execute(ServerConfig server, IReportStatus status, ConDepSettings settings, CancellationToken token)
   at ConDep.Dsl.Execution.ConDepConfigurationExecutor.<>c__DisplayClass10.<>c__DisplayClass13.<ExecutePreOps>b__f()
   at ConDep.Dsl.Logging.Logger.WithLogSection(String sectionName, Action action)
   at ConDep.Dsl.Execution.ConDepConfigurationExecutor.<>c__DisplayClass10.<ExecutePreOps>b__e()
   at ConDep.Dsl.Logging.Logger.WithLogSection(String sectionName, Action action)
   at ConDep.Dsl.Execution.ConDepConfigurationExecutor.ExecutePreOps(ConDepSettings conDepSettings, IReportStatus status, CancellationToken token)
   at ConDep.Dsl.Execution.ConDepConfigurationExecutor.Execute(ConDepSettings settings, IValidateClient clientValidator, IValidateServer serverValidator, ExecutionSequenceManager execManager, CancellationToken token)
[14:44:01][Step 1/1] Step Deploy (Command Line) failed
```

When I try to access https://******:4444/ConDepNode/api and check the certificate I find that the certificate validity dates have elapsed. For some reason the code that deletes the old certificates is not managing to execute correctly.

So far in order to resolve this issue I have created a small console application with the code from HttpApiSslCert.cs, X509CertBuilder.cs, CertificateHandler.cs. 
I then changed the code for ConfigureSslCert as follows:

``` csharp
        public static void ConfigureSslCert(string url)
        {
            var certStore = new X509Store(StoreLocation.LocalMachine);

            try
            {
                certStore.Open(OpenFlags.ReadWrite);

                CleanOldCerts(certStore);
                /*
                X509Certificate2 cert;

                if (!CertificateExist(certStore, out cert))
                {
                    cert = AddCertificate(certStore);
                }

                if (!CertificateBoundToIpAndPort(url, cert.GetCertHash()))
                {
                    BindCertificateToIpAndPort(cert, url);
                }*/
            }
            finally
            {
                certStore.Close();
            }
        }
```

and run it on the server using an administrator user. Once I do this and try to deploy again the app gets deployed correctly.

I'm not sure why the node is not removing the old certificates, I suspect it might be a rights issue, however I'm not sure how to confirm this. Have you seen this anywhere else?

Would it make sense that instead of deleting the old certificates, the node selects one which is valid for the current date?

**Comment by torresdal** [comment] 2016-03-18 17:24
I'll have look at this during the weekend. Someone mentioned to me that
deleting the old cert caused condep to generate a new valid cert. This is
not confirmed, but could be a alternative workaround. This bug must of
course be resolved. Thanks for reporting the issue.

Jon

fre. 18. mar. 2016 kl. 14.52 skrev Ruben Mamo notifications@github.com:

**Comment by JohnBloom** [comment] 2016-03-22 19:15
We are currently running into this issue as well. @torresdal any updates? Where would we find the certificate if we wanted to try that workaround?

**Comment by torresdal** [comment] 2016-03-22 21:52
@kjelliverb do you have any more details on what you guys did?

I'm currently on easter holiday and unfortunately didn't get time to look at this during the weekend. If anybody have time to look into this and send a pull request, I'll be happy to merge it in. If not I will find some time the next couple of days.

**Comment by JohnBloom** [comment] 2016-03-22 21:57
I can confirm that deleting the certificate will cause condep to recreate it. The certificate was hard to find. 

I followed the directions here: https://msdn.microsoft.com/en-us/library/ms788967(v=vs.110).aspx

Once I enabled the snap-in, under `Personal > Certificates` I deleted the node.condep.io certificate. I reran condep and it recreated it with an expiration a year from now.

**Comment by kjelliverb** [comment] 2016-03-22 22:00
We did the exact same thing as a quick workaround. I am also on eastern
holiday at the moment, so will not be able to take a closer look at this
problem the next couple of days.

Kjell I

tir. 22. mar. 2016 kl. 22.57 skrev John Bloom notifications@github.com:

**Comment by torresdal** [comment] 2016-03-22 22:13
Thanks for verifying @JohnBloom and @kjelliverb . Looking at the code I think I see what's going on. Since @rubenmamo's tool worked (verifying that the code for deleting the cert works), I think the solution is as simple as closing the store before adding the new cert. The delete cert operation is probably not fulfilled until the store is closed.

Now that I have a probable solution I'll add a fix the next couple of days and publish a new nuget package. Would be great if anyone could verify after the fix, though that might be hard now if everyone used the workaround :-) Maybe a good time for a proper integration test... I'll keep you posted.

**Comment by druslee** [comment] 2016-03-22 23:00
I think the problem is in the `CertificateHandler.CleanOldCerts` code: 
`
if (cert.NotAfter <= DateTime.Now.AddDays(-7)) certStore.Remove(cert);
`

It won't remove the cert until 7 days after the cert has expired.

**Comment by rubenmamo** [comment] 2016-03-23 07:26
@druslee the code that deletes the certificates works ok. I think you misread that line, it deletes the certificate 7 days before it expires, not after.
@torresdal once the new version is out I'll see whether I can modify X509CertBuilder.MakeCertificate to generate an old expired certificate so I can test the fix works. I have some test servers I can use to test this on.

**Comment by brigs** [comment] 2016-04-02 09:25
Hi :) I just submitted a PR that should fix this problem.

**Comment by rubenmamo** [comment] 2016-10-20 14:49
Hi, I just encountered this issue again. Was this fixed?

**Comment by kjelliverb** [comment] 2016-10-20 14:53
Hi!

This issue is solved. You must update ConDep.Node to latest version.

Kjell I

tor. 20. okt. 2016 kl. 16.49 skrev Ruben Mamo notifications@github.com:

**Comment by torresdal** [comment] 2016-10-20 15:01
As @kjelliverb mentioned this is solved. Closing.

**Closed as completed by torresdal** 2016-10-20 15:01 UTC

**Comment by rubenmamo** [comment] 2016-10-20 15:02
Thanks I will update to latest and see what happens
